version: '3.2'

x-base-cypress: &base-cypress
  image: "cypress/included:10.11.0"
  working_dir: /app-testing

services:
  local-packages:
    build:
      context: ./../
      dockerfile: ./bundlers-tests/packages.Dockerfile
      no_cache: true
    image: "local-packages:latest"
    profiles:
      - "local-packages"
  vite_test:
    build:
      context: .
      dockerfile: ./docker-tests/vite.Dockerfile
    ports:
      - "8080:80"
    profiles:
      - "vite"
      - "run-vite"
  cli_test:
    build:
      context: .
      dockerfile: ./docker-tests/cli.Dockerfile
    ports:
      - "8080:80"
    profiles:
      - "cli"
      - "run-cli"
  webpack_test:
    build:
      context: .
      dockerfile: ./docker-tests/webpack.Dockerfile
    ports:
      - "8080:80"
    profiles:
      - "webpack"
      - "run-webpack"
  nuxt_ssr_test:
    build:
      context: .
      dockerfile: ./docker-tests/nuxt-ssr.Dockerfile
    ports:
      - "8080:3000"
    profiles:
      - "nuxt-ssr"
      - "run-nuxt"
  nuxt_spa_test:
    build:
      context: .
      dockerfile: ./docker-tests/nuxt-spa.Dockerfile
    ports:
      - "8080:3000"
    profiles:
      - "nuxt-spa"
      - "run-nuxt"
  cypress_vite:
    <<: *base-cypress
    volumes:
      - ./docker-tests/vite:/app-testing
    depends_on:
      - vite_test
    environment:
      - CYPRESS_baseUrl=http://vite_test:80
    profiles:
      - "vite"
  cypress_cli:
    <<: *base-cypress
    volumes:
      - ./docker-tests/cli:/app-testing
    depends_on:
      - cli_test
    environment:
      - CYPRESS_baseUrl=http://cli_test:80
    profiles:
      - "cli"
  cypress_webpack:
    <<: *base-cypress
    volumes:
      - ./docker-tests/webpack:/app-testing
    depends_on:
      - webpack_test
    environment:
      - CYPRESS_baseUrl=http://webpack_test:80
    profiles:
      - "webpack"
  cypress_nuxt_ssr:
    <<: *base-cypress
    volumes:
      - ./docker-tests/nuxt-ssr:/app-testing
    depends_on:
      - nuxt_ssr_test
    environment:
      - CYPRESS_baseUrl=http://nuxt_ssr_test:3000
    profiles:
      - "nuxt-ssr"
  cypress_nuxt_spa:
    <<: *base-cypress
    volumes:
      - ./docker-tests/nuxt-spa:/app-testing
    depends_on:
      - nuxt_spa_test
    environment:
      - CYPRESS_baseUrl=http://nuxt_spa_test:3000
    profiles:
      - "nuxt-spa"
