version: '3.2'

x-base-cypress: &base-cypress
  image: "cypress/included:10.11.0"
  working_dir: /app-testing

services:
  local-vuestic:
    build:
      context: ./../
      dockerfile: ./bundlers-tests/vuestic.Dockerfile
    image: "local-vuestic:latest"
    profiles:
      - "local-vuestic"
  local-cli:
    build:
      context: ./../
      dockerfile: ./bundlers-tests/cli.Dockerfile
    image: "local-cli:latest"
    profiles:
      - "local-cli"
  local-nuxt:
    build:
      context: ./../
      dockerfile: ./bundlers-tests/nuxt.Dockerfile
    image: "local-nuxt:latest"
    profiles:
      - "local-nuxt"
  vite_test:
    build:
      context: .
      dockerfile: ./docker-tests/vite.Dockerfile
    ports:
      - "8080:80"
    profiles:
      - "vite"
      - "run-vite"
  cli_test:
    build:
      context: .
      dockerfile: ./docker-tests/cli.Dockerfile
    ports:
      - "8080:80"
    profiles:
      - "cli"
      - "run-cli"
  nuxt_test:
    build:
      context: .
      dockerfile: ./docker-tests/nuxt.Dockerfile
    ports:
      - "8080:3000"
    profiles:
      - "nuxt"
      - "run-nuxt"
  cypress_vite:
    <<: *base-cypress
    volumes:
      - ./docker-tests/vite:/app-testing
    depends_on:
      - vite_test
    environment:
      - CYPRESS_baseUrl=http://vite_test:80
    profiles:
      - "vite"
  cypress_cli:
    <<: *base-cypress
    volumes:
      - ./docker-tests/cli:/app-testing
    depends_on:
      - cli_test
    environment:
      - CYPRESS_baseUrl=http://cli_test:80
    profiles:
      - "cli"
  cypress_nuxt:
    <<: *base-cypress
    volumes:
      - ./docker-tests/nuxt:/app-testing
    depends_on:
      - nuxt_test
    environment:
      - CYPRESS_baseUrl=http://nuxt_test:3000
    profiles:
      - "nuxt"
